TRUNCATE TABLE atm;

INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('902', 'Opteva 522', 'АО "Казтелерадио"', 'г. Алматы, ул. Аль-Фараби, д.118А', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('1017', 'Cashway pilot', 'ЦБО №7 (134010)', 'пр. Абая 127/99А', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('1026', 'Cashway pilot', 'ЦПС №23 (134026)', 'ул. Жандосова, 25', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('1141', 'Cashway pilot', 'отделение №131435', 'Туркебаева 92', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('1223', 'Cashway pilot', 'отделение №131424', 'ул. Толе би, 159, уг. ул. Исаева', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('1420', 'Opteva 562', 'Аптека Pharmaplus', 'г.Алматы, ул.Ауэзова, 65', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('1755', 'Opteva 562', 'АО"Казахфильм" имени Шакена Айманова', 'пр. Аль-Фараби, 176', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('2446', 'Cashway pilot', 'ЦПС 10', 'Розыбакиева 247А, ТРК "Мега Центр"', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13001', 'Diebold Nixdorf C2560 (межстенный)', 'отделение №131505', 'Казахфильм 14', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13002', 'GRG H68VL', 'ТРЦ "Глобус", цоколь', 'пр. Абая, 109 "в"', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13006', 'NCR-6634 cash-in', 'ЦБО №7 (134010)', 'пр. Абая 127/99А', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13020', 'Diebold Nixdorf C2560 (межстенный)', 'ЦПС №62 (131501)', 'г. Алматы, пр. Гагарина 167, отделение №131501', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13021', 'GRG H68VL', 'БЦ «Esentai Mall»', 'Алматы пр. Аль-Фараби 77/8', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13023', 'GRG H68VL', 'Ялян', 'ул. Северное кольцо, 9', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13025', 'NCR-6622', 'Центральный офис АлмаТВ', 'ул.Айтиева, 23', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13026', 'GRG H68VL', 'Супермаркет "Magnum"', 'г. Алматы, ул. Радостовца, 292 (в зоне самообслуживания)', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13028', 'GRG H68VL', 'TOI Mart', 'Розыбакиева №4', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13031', 'WN ProCash 2150xe USB', 'отделение №131424', 'Толе би 159', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13032', 'GRG H68VL', 'рынок Байсат', 'ул. Северное кольцо, 7', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13034', 'NCR-6626', 'магазин Келеке', 'ул. Розыбакиева, 153а', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13038', 'Diebold Nixdorf C2560 (межстенный)', 'отделение №131422', 'ул.Жандосова,47, уг. Садовникова', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13043', 'GRG H68VL', 'TOI Mart', 'Розыбакиева №4', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13046', 'GRG H68VL', 'рынок Байсат', 'ул. Северное кольцо, 7', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13047', 'WN ProCash 2150хе', 'отделение №131509', 'м-н Коктем-2, 1', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13052', 'NCR-6626', 'Отделение №131861 ул. Гоголя, 144/99, уг. ул. Муратбаева', 'ул.Гоголя,144/99', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13059', 'Diebold Nixdorf C2560 (межстенный)', 'отделение №131505', 'Казахфильм 14', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13060', 'WN ProCash 2150хе', 'АОФ АО "Народный Банк Казахстана"', 'ул.Розыбакиева 101', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13062', 'NCR-6634 cash-in', 'отделение №131827', 'Байтурсынова 72', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13066', 'NCR-6622', 'Медицинский университет', 'ул. Богенбай батыра, 151', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13072', 'Diebold Nixdorf C2560 (межстенный)', 'ЦПС №15 (134001)', 'ул.Розыбакиева,281, ниже Аль-Фараби', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13074', 'WN ProCash 2000xe', 'ТОО "Темирбетон"', 'ул. Бокейханова, 11', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080', 'NCR-6626', 'отделение №131861', 'ул. Гоголя, 144, уг. ул. Муратбаева', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13082', 'NCR-6626', 'отделение №131861', 'ул. Гоголя, 144, уг. ул. Муратбаева', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13088', 'GRG H68VL', 'супермаркет "SMALL"', 'ул. Жамбыла, 205', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13089', 'NCR-6632', 'рынок Сауран', 'пр. Рыскулова, 103', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13096', 'Diebold Nixdorf C2560 (межстенный)', 'ЦПС №10', 'г.Алматы, ул. Розыбакиева,247 а', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13098', 'WN ProCash 2150хе', 'отделение №131509', 'м-н Коктем-2, 1', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13101', 'NCR-6622', 'КазГУ, в здание магнум дайли', 'пр. Аль-Фараби, 71/21', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13103', 'Diebold Nixdorf C2560 (межстенный)', 'ЦПС №62 (131501)', 'г. Алматы, пр. Гагарина 167, отделение №131501', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13106', 'NCR-6626', 'отделение №131599', 'м-н Алмагуль 44', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13109', 'DN200', 'Политех главный корпус со стороны ул. Байтурсынова', 'ул. Сатпаева, 22', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13112', 'GRG H68VL', 'ТД "Алатау-2"', 'г.Алматы, ул. Северное кольцо, 23', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13116', 'GRG H68VL', 'ЦПС №6 (131530)', 'ул. Абая 109В', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13117', 'NCR-6622', 'супермаркет Магнум', 'мкр. Казахфильм, 17', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13118', 'NCR-6634 cash-in', 'ЦБО №7 (134010)', 'пр. Абая 127/99А', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13123', 'NCR 6626', 'Магазин "Строймарт"', 'пр. Гагарина, 244 "а"', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13128', 'ProCash 2050', 'магазин "Асия"', 'мкр. Ерменсай, ул. Жангир хана, 101', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13133', 'Procash 2050', 'Аптека Низких цен', 'мкр.Казахфильм, ул. Мамыр, 1/ Исиналиева, 1/1', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13135', 'ProCash 2050', 'Kegoc', 'ул. Шевченко, 162/7', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13146', 'WN ProCash 2050xe', 'Алматы Су', 'ул. Жарокова, 196', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13152', 'GRG H68VL', 'ТК Акбаулак 3', 'мкр.Заря-Восток, ул.Головацкого 41', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13156', 'NCR-6626', 'отделение №131599', 'Алмагуль 44', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13165', 'WN ProCash 2150xe', 'отделение №131422', 'ул.Жандосова,47, уг. Садовникова', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13167', 'WN ProCash 2150хе', 'отделение №131424', 'Толе би 159', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13172', 'WN ProCash 2150хе', 'отделение №131509', 'м-н Коктем-2, 1', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13184', 'GRG H68VL', 'Магнум', 'ул. Муратбаева, 63', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13188', 'Diebold Nixdorf C4060', 'ТЦ "Акбулак 3" возле Евразии', 'Северное кольцо, 12', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13193', 'GRG H68VL', 'отделение №131435', 'ул. Туркебаева, 92', 'Сектор C');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13196', 'GRG H68VL', 'ТРК "MAXIMA"', 'Райымбека 239Г', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13200', 'GRG H68VL', 'отделение №131435', 'Туркебаева 92', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13201', 'GRG H68VL', 'отделение №131435', 'Туркебаева 92', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13204', 'GRG H68VL', 'ЦБО №7 (134010)', 'пр. Абая 127/99А', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13207', 'GRG H68VL', 'отделение №131435', 'Туркебаева 92', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13212', 'NCR-6626', 'БЦ ТОО "Гимарат Сервис"', 'Карасай батыра 98', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13215', 'GRG H68VL', 'отделение №131422, ЦПС 35', 'ул.Жандосова,47, уг. Садовникова', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13224', 'WN ProCash 2150xe', 'QazaqGaz Aimaq', 'пр. Т. Рыскулова, 99', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13225', 'GRG H68VL', 'ТРЦ "Максима"', 'пр. Райымбека, 239а', 'Сектор C');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13227', 'Diebold Nixdorf C2560 (межстенный)', 'АОФ АО "Народный Банк Казахстана"', 'Розыбакиева 101', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13229', 'WN ProCash 2150хе', 'отделение №131827', 'Байтурсынова 72', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13253', 'GRG H68VL', 'ЦПС №23 (134026)', 'г.Алматы, ул.Жандосова, д.25', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13255', 'NCR-6622', 'стройрынок Саламат', 'ул. Розыбакиева, 72а', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13261', 'NCR 6626', 'Международный институт информационных технологий', 'ул. Манаса, 34/1', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13265', 'NCR-6622', 'СРК Баганашыл, Cofee Bar Zenit', 'ул. Санаторная, 14а', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13266', 'NCR 6626', 'отделение №131505', 'Казахфильм 14', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13269', 'GRG H68VL', 'Супермаркет Small', 'г. Алматы, ул. Ади Шарипова, 63а', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13271', 'NCR 6628', 'Манхэттен', 'Прокофьева 140', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13272', 'NCR-6632cash-in', 'Глобус, отделение Алтын банк', 'Абая 109В', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13273', 'NCR-6634 cash-in', 'ТД "АРЕНА" Межстенный АТМ.', 'г.Алматы пр.Абая д.141', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13274', 'NCR-6632cash-in', 'Отель "Рахат-Палас"', 'ул. Сатпаева, 29/6', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13275', 'NCR-6632 cash-in', 'Детская инфекционная больница', 'ул. Байзакова, 299А', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13276', 'NCR-6634 cash-in', 'АОФ АО "Народный Банк Казахстана"', 'ул. Розыбакиева, 101, уг. ул. Сатпаева', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13298', 'Diebold Nixdorf C4060', 'ЦБО №7 (134010)', 'пр. Абая 127/99А', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13301', 'Diebold Nixdorf C4060', 'Avtodom', 'ул. Сатпаева, 90/22', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13303', 'Diebold Nixdorf C4060', 'отделение №131861', 'ул. Гоголя, 144, уг. ул. Муратбаева', 'Сектор C');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13317', 'DN200', 'ЦПС №23 (134026)', 'ул. Жандосова, 25', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13321', 'NCR 6628', 'АЗС Баганашыл', 'ул. Сыргабекова, 1 Д', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13330', 'Diebold Nixdorf C4060', 'ТД "Рамстор", Атакент, 1-й этаж', 'ул. Тимирязева, 42', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13332', 'Diebold Nixdorf C4060', 'ТД Алатау', 'пр. Рыскулова, 103/3', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13333', 'Cashway pilot', 'ЦПС №6 (131530)', 'ул. Абая 109В', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13334', 'Diebold Nixdorf C4060', 'ТРЦ "Атакент Mall" Студент', 'г. Алматы, ул.Тимирязева, 42', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13335', 'Diebold Nixdorf C2560 (межстенный)', 'ЦПС №10', 'г.Алматы, ул. Розыбакиева,247 а', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13337', 'Diebold Nixdorf C4060', 'ТД "Alma city"', 'ул. Северное кольцо, 19', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13341', 'Diebold Nixdorf C4060', 'БЦ "Волков-Геология"', 'ул. Богенбай батыра, 168', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13343', 'Diebold Nixdorf C4060', 'Центральная больница №12', 'ул. Жандосова, 6', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13348', 'Diebold Nixdorf C4060', '«Рахат Тауэрс»', 'Байзакова 280', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13349', 'GRG H68VL', 'ТД "Магнум"', 'ул. Розыбакиева 70', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13353', 'Diebold Nixdorf C4060', 'рынок Рахат', 'ул. Северное кольцо, 15', 'Сектор C');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13356', 'GRG H48VD', 'ТД "Коктем", вдоль Весновки', 'мкр. Коктем-1, д.20', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13357', 'Diebold Nixdorf C4060', 'Казгипронефтетранс', 'пр. Райымбека, 160', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13358', 'Diebold Nixdorf C4060', 'г.Алматы, ул.Байзакова, 303', 'ХАБА ООН', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13360', 'Diebold Nixdorf C4060', 'БЦ Promenade Business Park', 'пр. Абая, 44а', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13384', 'Diebold Nixdorf C4060', 'Супермаркет Orange', 'ул. Байтурсынова, 179к6', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13388', 'Diebold Nixdorf C4060', 'ГБ АГФ, концелярия', 'г. Алматы, пр. Гагарина, 135Ж, вход со стороны Гагарина', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13390', 'Diebold Nixdorf C4060', 'Ulttyq marqet', 'ул. Утепова, 31', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13391', 'Diebold Nixdorf C4060', 'ТОО «RG Brands Kazakhstan»', 'г. Алматы, пр. Райымбека, 212Б', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13394', 'Diebold Nixdorf C4060', 'ЦБО №7 (134010)', 'пр. Абая 127/99А', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13395', 'Diebold Nixdorf C4060', 'ТРЦ "АДК"', 'г.Алматы, ул.Сатпаева, д.90 (ближе к паркингу ближе к ул.Брусиловского)', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13411', 'Diebold Nixdorf C2560 (межстенный)', 'отделение №131509', 'м-н Коктем-2, 1', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13418', 'Diebold Nixdorf C4060', 'Национальный Банк РК, 2-ой подъезд, 2-ой этаж', 'м-н Коктем-3, 21', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13420', 'Diebold Nixdorf C4060', 'ТД "Алатау-6"', 'г.Алматы, ул. Северное кольцо, 50', 'Сектор C');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13427', 'Diebold Nixdorf C2560 (межстенный)', 'отделение №131599', 'Алмагуль, 44', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13430', 'Diebold Nixdorf C4060', 'ТОО «Хозяйственное управление города Алматы»', 'г.Алматы, ул. Байзакова, 303', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13431', 'Diebold Nixdorf C4060', 'Рамстор- Алмагуль', 'мкр. Алмагуль, д.18 "а"', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13434', 'Diebold Nixdorf C4060', 'ТЦ "Акбулак", за ТД Саяхат', 'ул. Северное кольцо, б/н', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13436', 'Diebold Nixdorf C2590 (островной)', 'ЦПС №23 (134026)', 'ул. Жандосова, 25', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13441', 'Diebold Nixdorf C2590 (островной)', 'отделение №131520', 'Сатпаева 78', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13444', 'GRG H48VD', 'Магазин "Технодом"', 'ул. Жандосова, 34а', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13447', 'Diebold Nixdorf C2590 (островной)', 'Бизнес центр Каусар', 'ул.Толеби, 286/4', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13451', 'Diebold Nixdorf C2560 (межстенный)', 'отделение №131827', 'Байтурсынова 72', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13452', 'DN200', 'Санаторий Koktem resort (Ремизовка)', 'Аскартау микрорайон', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13455', 'Diebold Nixdorf C4060', 'ТД "Магнум"', 'ул. Толе би, 229', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13457', 'Diebold Nixdorf C4060', 'супермаркет "Toimart"', 'ул. Жандосова, 21', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13465', 'Diebold Nixdorf C4060', 'ТОО "SinoOil"', 'ул. Муратбаева, 147', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13468', 'Diebold Nixdorf C2560 (межстенный)', 'отделение №131424', 'ул. Толе би, 159, уг. ул. Исаева', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13472', 'Diebold Nixdorf C2560 (межстенный)', 'ТОО "Технодом"', 'ул. Курмангазы, 178 "а"', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13473', 'Diebold Nixdorf C2590 (островной)', 'ЦБО №7', 'г. Алматы, ул. Пр. Абая, 127/99А уг.Жарокова', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13485', 'Diebold Nixdorf C2590 (островной)', 'ЦПС №23 (134026)', 'ул. Жандосова, 25', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13486', 'Diebold Nixdorf C2590 (островной)', 'ВДНХ', 'ул. Тимирязева, 40', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13491', 'Diebold Nixdorf C2590 (островной)', 'супермаркет Small', 'ул. Розыбакиева 75', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13493', 'Diebold Nixdorf C2590 (островной)', 'Coca Cola', 'г.Алматы,ул. Байзакова, 73, уг. ул. Гоголя 203', 'Сектор C');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13510', 'GRG H48VD', 'ТД "City Center"', 'ул.Толеби, 136', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13518', 'GRG H48VD', 'РКО "Толе би"', 'ул. Толе би, 101', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13520', 'GRG H48VD', 'РКО "Толе Би"', 'ул. Толе би, 101', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13521', 'GRG H48VD', 'ТРК "City Centre"', 'ул. Толеби, 136', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13523', 'GRG H48VD', 'ТД Орион', 'ул. Ауэзова, 52', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13524', 'GRG H48VD', 'Манхэттен', 'Прокофьева 140', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13525', 'GRG H48VD', 'Академия Кайнар', 'Ул. Байзакова, 125/185', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13528', 'GRG H48VD', 'Рынок Жулдыз(оптовка), первый вход напротив АЖК', 'Ул. Розыбакиева 33/1', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13532', 'GRG H68V', 'отделение №131422', 'ул.Жандосова,47, уг. Садовникова', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13535', 'GRG H68VL', 'ТД "Коктем"', 'мкр. Коктем-1, д.20', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13537', 'GRG H68VL', 'Национальный банк РК, 1-ый подъезд, 1-ый этаж', 'мкр. Коктем-3, д.21', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13543', 'GRG H68V', 'магазин Дәстүр', 'г.Алматы,ул Северное кольцо,строение №8', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13546', 'GRG H68V', 'Аптека "Мелисса"', 'ул. Туркебаева, 92', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13549', 'GRG H68VL', 'АО "Народный Банк Казахстана", мантоварка', 'Абая 109Б', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13553', 'GRG H68VL', 'университет "AlmaU"', 'ул. Розыбакиева, 227', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13554', 'GRG H68VL', 'Мега 2 дальний паркинг', 'ул. Розыбакиева, 263, Мега Центр 2', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13560', 'GRG H68VL', 'ЦПС №6 (131530)', 'Абая 109В', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13571', 'GRG H68VL', 'Строительный рынок', 'пр. Рыскулова, 103 "в"', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13574', 'GRG H68VL', 'ТД "Алатау 2"', 'ул. Северное кольцо, 23', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13582', 'GRG H68VL', 'отделение №131599', 'Алмагуль, 44', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13583', 'GRG H68VL', 'Сулпак', 'ул. Толе би, 187', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13584', 'GRG H68VL', 'ТРЦ "АДК"', 'г.Алматы, ул.Сатпаева, д.90 (ближе к паркингу ближе к ул.Брусиловского)', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13585', 'GRG H68VL', 'ЦПС №23 (134026)', 'г.Алматы, ул.Жандосова, д.25', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13588', 'GRG H68VL', 'отделение №131509', 'м-н Коктем-2, 1', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13593', 'GRG H68VL', 'ТЦ "Maxima"', 'пр. Райымбека, 239 "г"', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13598', 'GRG H68VL', 'ТРЦ "АДК"', 'г.Алматы, ул.Сатпаева, д.90 (ближе к паркингу ближе к ул.Брусиловского)', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13599', 'GRG H68VL', 'Мини маркет"Royal Diamond_', 'ул. Казыбек Тауасарулы, 56', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13605', 'GRG H68VL', 'ЦПС №25 (134030)', 'ул.Толе би, 101', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13610', 'GRG H68VL', 'ЦПС №23 (134026)', 'г.Алматы, ул.Жандосова, д.25', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13615', 'GRG H68VL', 'БЦ "Алатау Гранд"', 'Тимирязева 28В', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13617', 'GRG H68VL', 'ЦПС 10', 'Розыбакиева 247А, ТРК "Мега Центр"', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13619', 'GRG H68VL', 'супермаркет "SMALL"', 'ул. Мынбаева, 44', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13620', 'GRG H68VL', 'TOO Magnum Cash&Carry', 'г.Алматы, ул.Радостовца д.292', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13625', 'GRG H68VL', 'отделение №131827', 'Байтурсынова 72', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13630', 'GRG H68VL', 'ЦБО №6', 'ул. Ауэзова, 175', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13631', 'GRG H68VL', 'ЦБО №6', 'ул. Ауэзова, 175', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13632', 'GRG H68VL', 'ЦБО №6', 'ул. Ауэзова, 175', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13633', 'GRG H68VL', 'ЦБО №6', 'ул. Ауэзова, 175', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13634', 'GRG H48VD', 'магазин «Раушан»', 'пр. Аль-Фараби, 110/19', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13639', 'GRG H48VD', 'Магазин Zeta', 'Пр. Райымбека 225', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13644', 'GRG H68VL', 'ЦПС 10', 'Розыбакиева 247А, ТРК "Мега Центр"', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13645', 'GRG H68VL', 'TOO Magnum Cash&Carry', 'г.Алматы, ул.Радостовца д.292', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13646', 'GRG H68VL', 'супермаркет Магнум', 'ул. Радостовца, 292', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13647', 'GRG H68VL', 'ЦБО №6', 'ул. Ауэзова, 175', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13656', 'GRG H68VL', 'ЦПС №35 (131422)', 'ул.Жандосова,47, уг. Садовникова', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13658', 'GRG H68VL', 'ТРЦ "АДК"', 'ул. Сатпаева, 90', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13665', 'GRG H68VL', 'ТЦ «Тоймарт»', 'ул. Розыбакиева, 4', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13669', 'GRG H68VL', 'ЦБО №7 (134010)', 'пр. Абая 127/99А', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13672', 'GRG H68VL', 'ЦПС №4 (130079)', 'г. Алматы, ул. Розыбакиева 101, ЦПС №4', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13673', 'GRG H68VL', 'ЦПС №23 (134026)', 'г. Алматы, ул. Жандосова, 25', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13674', 'GRG H68VL', 'ТРК "Mega Center Alma-Ata - 2"', 'г.Алматы, ул.Розыбакиева, 263 (мега 2 круглосуточная АТМ зона, 1-ый с левой стороны)', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13682', 'GRG H68VL', 'ТРЦ "Мега"', 'ул. Розыбакиева, 247а', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13685', 'GRG H68VL', 'ТРЦ "Глобус", цоколь', 'пр. Абая, 109 "в"', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13687', 'GRG H68VL', 'ТРЦ "Есентай Малл"', 'пр. Аль-Фараби, 77/7', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13688', 'GRG H68VL', 'ТРЦ «Esentai Mall»', 'Аль-Фараби, 77 БЦ «Esentai Mall»', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13050001', 'АПП 2', 'ЦБО №7 (134010)', 'пр. Абая 127/99А', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13050014', 'АПП 2', 'ЦПС №23 (134026)', 'г.Алматы, ул.Жандосова, д.25', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13050015', 'АПП 2', 'ЦПС №23 (134026)', 'г.Алматы, ул.Жандосова, д.25', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13050023', 'АПП 2', 'АОФ Юр. Отделение', 'г. Алматы, ул. Розыбакиева 101, Юр. отделение', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13050028', 'АПП 2', 'ЦБО №6 (134005)', 'г.Алматы, ул.Ауезова, д.175', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13060005', 'АПП 2', 'ЦПС №25 (134030)', 'ЦПС 25 г.Алматы, ул. Толе би, 101', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13060008', 'АПП 2', 'ЦПС №4 (130079)', 'г. Алматы, ул. Розыбакиева 101, ЦПС №4', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13060014', 'АПП 2', 'ЦПС №25 (134030)', 'Tole bi 101 Dulwich Br', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13060016', 'АПП-2', 'ЦПС №44 (131599)', 'Алмагуль, 44', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13060025', 'АПП-2', 'ЦПС №6 (131530)', 'ул. Абая 109В', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13060029', 'АПП-2', 'ЦПС №44 (131599)', 'Алмагуль, 44', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13060032', 'АПП 2', 'ЦПС №6 (131530)', 'ул. Абая 109В', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080003', 'БТС-3', 'ЦПС №39 (131435)', 'ул. Васнецова, 27/92', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080004', 'БТС-3', 'ЦПС №39 (131435)', 'ул. Васнецова, 27/92', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080005', 'БТС-3', 'ЦПС №41 (131509)', 'м-н Коктем-2, 1', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080008', 'БТС-3', 'ЦПС №41 (131509)', 'м-н Коктем-2, 1', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080009', 'БТС-3', 'ЦПС №4 (130079)', 'г. Алматы, ул. Розыбакиева 101, ЦПС №4', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080010', 'БТС-3', 'ЦПС №48 (131827)', 'г.Алматы, ул. Байтурсынова, 72 уг. Шевченко, РКО № 131827', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080018', 'БТС-3', 'АГФ Жандосова Гагарина, отделение 134026, вход со стороны Юр. отделения', 'ул.Гагарин көшесі, 135/8', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080020', 'БТС-3', 'ЦПС №56', 'Отделение №131861 ул. Гоголя, 144/99, уг. ул. Муратбаева', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080023', 'БТС-3', 'ЦПС №35 (131422)', 'ул.Жандосова,47, уг. Садовникова', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080026', 'БТС-3', 'ЦПС №35 (131422)', 'ул.Жандосова,47, уг. Садовникова', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080035', 'АПП-3', 'ЦБО №7 (134010)', 'пр. Абая 127/99А', 'Сектор B');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080037', 'IqOffice', 'ЦПС №36', 'г.Алматы, ул. Толе би, 159 уг. Мирзояна, РКО № 131424', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080038', 'IqOffice', 'АОФ Юр. Отделение', 'г. Алматы, ул. Розыбакиева 101, Юр. отделение', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080041', 'IqOffice', 'ЦПС №36', 'г.Алматы, ул. Толе би, 159 уг. Мирзояна, РКО № 131424', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080050', 'БТС-3', 'ЦПС №39', 'ул. Васнецова, 27/92', 'Сектор С');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080059', 'БТС-3', 'РКО №131505', 'Казахфильм 14', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080062', 'АПП-3', 'ЦПС №10', 'г.Алматы, ул. Розыбакиева 247а, Мегацентр ЦПС10', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080064', 'АПП-3', 'ЦПС №10', 'г.Алматы, ул. Розыбакиева 247а, Мегацентр ЦПС10', 'Сектор А');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080070', 'АПП-3', 'Глобус, отделение Алтын банка', 'г.Алматы, пр. Абая, 109В', 'Сектор В');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080073', 'АПП-3', 'ЦПС №62 (131501)', 'г. Алматы, пр. Гагарина 167, отделение №131501', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13080077', 'АПП-3', 'ЦПС №26 (134032)', 'г. Алматы, пр-кт Аль-Фараби, д. 77/7', 'Сектор A');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('13000', 'AdiAP', 'ЦПС №26 (134032)', 'г. Сарсенов Бауржан д. 77/7', 'Сектор Г');
INSERT INTO atm (atm_number, model, organization, address, sector) VALUES ('130001', 'AdiAP', 'ЦПС №26 (134032)', 'г. Сарсенкулов Бауржан д. 77/7', 'Сектор Г');

SELECT COUNT(*) as loaded_atm_count FROM atm;
