bot.name=atmtesting_bot
bot.key=8891378059:AAFKLggIq1OdrQ1OqXgoxQAStwoc-6urhXk
bot.enabled=true
debug=false

spring.datasource.url=jdbc:postgresql://localhost:5432/ATMDatabase
spring.datasource.username=postgres
spring.datasource.password=2231
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false
