spring.application.name=ShaxzadBot

bot.name=atm_address_bot
bot.key=8721590487:AAGdOLxYfncTJVvd7EKo02pI0lmL6SIBlC8
bot.enabled=true
debug=false

# spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://194.238.40.155:5432/shaxzad_bot?sslmode=disable
spring.datasource.username=shaxzad
spring.datasource.password=Admission2021
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false

logging.level.root=INFO
logging.level.Bot.ShaxzadBot=DEBUG
logging.level.org.springframework.boot=INFO
logging.file.name=logs/app.log
