spring.application.name=ShaxzadBot

bot.name=atmtesting_bot
bot.key=8721590487:AAGdOLxYfncTJVvd7EKo02pI0lmL6SIBlC8
bot.enabled=true
debug=false

# spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/shaxzad_bot
spring.datasource.username=shaxzad
spring.datasource.password=Admission2021
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false
